### ISSUE TITLE
Invalid typespec

### ISSUE THREAD

**Issue by epinault** [bitwalker/uniq#17]
While using dialyzer and this library, it appears that the typespec is incorrect, submitted #16  to try to fix it. Let me know what you think

**Comment by edisonywh** [comment]
we need this as well, anything we can do to push this along?

**Comment by epinault** [comment]
@bitwalker anything we can do to help for this MR or need more help with this repo?

**Comment by bitwalker** [comment]
The PR is merged, I'll get a new release out as soon as I have a moment. Sorry for the delay!

**Comment by epinault** [comment]
thank you!
